# Documentation:
# https://bioconductor.org/packages/devel/bioc/vignettes/onlineFDR/inst/doc/theory.html

library(dplyr)
library(onlineFDR)

df <- read.csv(file.choose())  # test_data_large.csv

# Generated by:
# p_vals, batch_sizes = generate_test_data(n=1_000, h0_prop=0.025, max_batch_size=15, seed=1)

# test_batch.py (_large)

# Batch BH
res <- onlineFDR::BatchBH(df, alpha=.05)
sum(res$R)  # 19

result <- res %>%
  group_by(batch) %>%
  summarise(unique_sum = sum(unique(alphai)))

sum(result$unique_sum)  # 0.8400105

# Batch BH-Storey
res <- onlineFDR::BatchStBH(df, alpha=.05, lambda=0.25)
sum(res$R)  # 19

result <- res %>%
  group_by(batch) %>%
  summarise(unique_sum = sum(unique(alphai)))

sum(result$unique_sum)  # 0.8751455

# Batch PRDS
res <- onlineFDR::BatchPRDS(df, alpha=.05)
sum(res$R)  # 19

result <- res %>%
  group_by(batch) %>%
  summarise(unique_sum = sum(unique(alphai)))

sum(result$unique_sum)  # 0.05037012
