[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "online-fdr"
version = "0.0.1"
description = "Online Hypothesis Testing."
authors = [
  { name = "Oliver Hennhoefer", email = "oliver.hennhoefer@mail.de" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.12"
dependencies = [
]

[project.urls]
"Homepage" = "https://github.com/OliverHennhoefer/online-fdr"